apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  replicas: 3
  selector:
#Labels used to link deployment to pods
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
#Labels that will be assigned to pods
        app: web-server
    spec:
      containers:
      - name: server
        image: nginx:1.7.9
