apiVersion: v1
kind: Service
metadata:
  name: web-app-external
  annotations:
    training: EKS101
spec:
  ports:
#Service port
  - port: 80
#Pod port
    targetPort: 80
  type: LoadBalancer
  selector:
#Labels used to link service to pods
    app: web-server

# NLB Annotations
# https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html#load-balancer-instance
