apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  ports:
#Service port
  - port: 80
#Pod port
    targetPort: 80
  type: LoadBalancer
  selector:
#Labels used to link service to pods
    app: web-server
